apiVersion: eksctl.io/v1alpha5
kind:  ClusterConfig

metadata:
  name:  ekscluster
  region: ap-south-1


nodeGroups:
   - name: ekscluster-ng1
     desiredCapacity: 3
     instanceType: t2.micro
     ssh:
        publicKeyName: key11



---------------------------------------------------------------------
#launched using spot instances
apiVersion:  eksctl.io/v1alpha5
kind:  ClusterConfig


metadata:
  name:  ekscluster
  region: ap-south-1


nodeGroups:
   - name: joomla1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: key11
     


   - name: joomla2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: key11
   
   - name: ng-mixed
     minSize: 2
     maxSize: 5
     instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
     ssh:
        publicKeyName: key11