apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: nishanpass
  literals:
  - password=nishanroot
resources:
  - deployment-mysql.yaml
  - deployment-joomla.yaml

